let activeCharacter = 0;

const characters = [
  {
    id: 0,
    displayName: "Cyrus",
    profileText: ` The responsible head butler of the Dietrich household.<br /><br />He is a former human turned into a vampire by the previous lord of the Dietrich family, and is thus bound to serve them for the rest of his immortal life.`,
    story: "coming soon!",
    likes: "Peace and quiet, sweet treats",
    dislikes: "Irresponsible individuals",
    defaultImage: "./assets/cyrus/cyrus_default.webp",
    bgImage: "../assets/cyrus_bedroom_v2.png",
    images: [
      "./assets/cyrus/cyrus_default.webp",
      "./assets/cyrus/cyrus_angry_blush.webp",
      "./assets/cyrus/cyrus_angry.webp",
      "./assets/cyrus/cyrus_cry.webp",
      "./assets/cyrus/cyrus_embarrass.webp",
      "./assets/cyrus/cyrus_fakesad.webp",
      "./assets/cyrus/cyrus_fear.webp",
      "./assets/cyrus/cyrus_hurt.webp",
      "./assets/cyrus/cyrus_shy.webp",
      "./assets/cyrus/cyrus_sigh.webp",
      "./assets/cyrus/cyrus_sleep.webp",
      "./assets/cyrus/cyrus_smile.webp",
      "./assets/cyrus/cyrus_speak.webp",
      "./assets/cyrus/cyrus_child.webp",
      "./assets/cyrus/cyrus_child_speak.webp",
    ],
  },
  {
    id: 1,
    displayName: "Mikael",
    profileText: `The arrogant young lord of the noble Dietrich family, who recently took on the title after his father's passing.<br><br>He enjoys seeking a thrill and his favourite pastime is making inappropriate advances on his butler, Cyrus, much to Cyrus’s irritation.`,
    story: "coming soon!",
    likes: "Cyrus, showing off",
    dislikes: "Tedious work",
    defaultImage: "./assets/mikael/mikael_default.webp",
    bgImage: "../assets/mikael_bedroom.webp",
    images: [
      "./assets/mikael/mikael_default.webp",
      "./assets/mikael/mikael_angry.webp",
      "./assets/mikael/mikael_concern.webp",
      "./assets/mikael/mikael_embarrass.webp",
      "./assets/mikael/mikael_evil.webp",
      "./assets/mikael/mikael_evilV2.webp",
      "./assets/mikael/mikael_happy.webp",
      "./assets/mikael/mikael_panic.webp",
      "./assets/mikael/mikael_shy.webp",
      "./assets/mikael/mikael_sigh.webp",
      "./assets/mikael/mikael_speak.webp",
      "./assets/mikael/mikael_upset.webp",
      "./assets/mikael/mikael_outfit.webp",
      "./assets/mikael/mikael_outfit_speak.webp",
      "./assets/mikael/mikael_outfit_ruby_speak.webp",
      "./assets/mikael/mikael_outfit_ruby.webp",
      "./assets/mikael/mikael_child.webp",
      "./assets/mikael/mikael_child_sad.webp",
      "./assets/mikael/mikael_child_speak.webp",
    ],
  },
];
